services:

  app:
    container_name: task-management-system
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=My_passw0rd
    ports:
      - 8080:8080

  postgres_db:
    container_name: task_management_system_db
    image: postgres:16rc1-alpine
    environment:
      - POSTGRES_PASSWORD=My_passw0rd
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
