spring:
  activemq:
    user: admin
    password: admin
    web-to-crud-queue: "Web->Server"
    client-id: "Spring Boot Web App"
    broker-url: tcp://localhost:61616
    packages:
      trusted: org.springframework.remoting.support,java.lang,dev.trifanya.spring_webapp
logging:
  level:
    org.springframework.web: INFO
    dev.trifanya.spring_webapp: TRACE

